default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blogapp_development

test:
  <<: *default
  database: blogapp_test

production:
  primary:
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    url: <%= ENV['CACHE_DB_URL'] %>
    migrations_paths: db/cache_migrate
  queue:
    url: <%= ENV['QUEUE_DB_URL'] %>
    migrations_paths: db/queue_migrate
  cable:
    url: <%= ENV['CABLE_DB_URL'] %>
    migrations_paths: db/cable_migrate
